name: Hello World Workflow

on:
  push:
    branches:
      -main 
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo hello worlddd!
        shell: bash
  googbye:
    runs-on: ubuntu-latest
    steps:
      - name : googbye world
        run : echo GoodBye world
        shell: bash
      
