name: Create a name on new issues

on:
  issues:
    types: [opened]
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
    - name: "dump github context"
      run: echo '${{toJSON(github.event)}}' | jq
      shell: bash
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
          issue-number: ${{github.event.issue.number}}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
          
  comment-with-api:
      runs-on: ubuntu-latest
      steps:
        - name:  Create comment with API
          run: |
            gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${OWNER}/{REPO}/issues/${ISSUE_NUMBER}/comments \ 
            -f body='
             Comment but from the API call not action
             '
          env:
            GITHUB_TOKEN: ${{secrets.MY_TOKEN}}
            OWNER: ${{github.event.organization.login}}
            REPO: ${{github.event.respository.name}}
            ISSUE_NUMBER: ${{github.events.issue.number}}
      
    
